name: Build and check image
on:
  push:
    branches: ["master"]
    paths:
      - "docker/**"
      - ".github/workflows/**"
  pull_request:
    branches: ["master"]
    paths:
      - "docker/**"
      - ".github/workflows/**"

permissions:
  contents: write
  packages: write

env:
  REGISTRY: ghcr.io
  LATEST_TAG: ghcr.io/rootshell-coder/drawio-exporter:latest
  TRIVY_SECURITY: SECURITY.txt

jobs:
  build:
    name: Publish to github registry
    runs-on: [ubuntu-24.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: docker
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
          platforms: linux/amd64
          tags: |
            ${{ env.LATEST_TAG }}

  check:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    needs: [build]
    name: Pull image
    runs-on: [ubuntu-24.04]
    steps:
      - uses: actions/checkout@v4
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Check security
        run: |
          docker pull ${{ env.LATEST_TAG }}
          docker run --rm ghcr.io/rootshell-coder/trivy-cached:latest image ${{ env.LATEST_TAG }} --skip-db-update > ${{ env.TRIVY_SECURITY }}

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          author_name: RootShell-coder
          author_email: Root.Shelling@gmail.com
          message: "upd"
          add: "*.txt"
